# Generated by Django 5.0.6 on 2025-04-28 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_x', models.IntegerField()),
                ('dimension_y', models.IntegerField()),
            ],
            options={
                'db_table': 'Map',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='CategoryElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_Category_Elements', to='core.category')),
            ],
            options={
                'db_table': 'CategoryElement',
            },
        ),
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_top_left_X', models.IntegerField()),
                ('position_top_left_Y', models.IntegerField()),
                ('position_bottom_right_X', models.IntegerField()),
                ('position_bottom_right_Y', models.IntegerField()),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_Map_Bars', to='core.map')),
            ],
            options={
                'db_table': 'Bar',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_Menu_Categories', to='core.menu'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_column='email', max_length=254, unique=True, verbose_name='Email Address')),
                ('profile_picture', models.ImageField(blank=True, db_column='profile_image', default='core/perfil_predeterminado.jpg', null=True, upload_to='profile/', verbose_name='Profile Picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='get_User_Profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='restaurant_icons/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_Profile_Restaurantes', to='core.profile')),
            ],
            options={
                'db_table': 'Restaurante',
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_Restaurante_Menus', to='core.restaurante'),
        ),
        migrations.AddField(
            model_name='map',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_Restaurante_Maps', to='core.restaurante'),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('type', models.IntegerField(choices=[(2, 'Double'), (4, 'Familiar'), (6, 'Familiar Numerous'), (8, 'Meeting')])),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_Map_Tables', to='core.map')),
            ],
            options={
                'db_table': 'Table',
            },
        ),
        migrations.CreateModel(
            name='TableOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('category_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_CategoryElement_Orders', to='core.categoryelement')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_Table_Orders', to='core.table')),
            ],
            options={
                'db_table': 'TableOrder',
            },
        ),
        migrations.CreateModel(
            name='OrderState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Waiting confirmation', 'Waiting confirmation'), ('Waiting to be cooked', 'Waiting to be cooked'), ('Waiting to be delivered', 'Waiting to be delivered')], max_length=50)),
                ('table_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_TableOrder_OrderStates', to='core.tableorder')),
            ],
            options={
                'db_table': 'OrderState',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_code', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('Waiter', 'Waiter'), ('Chef', 'Chef')], max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_Restaurante_Workers', to='core.restaurante')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_Profile_Workers', to='core.profile')),
            ],
            options={
                'db_table': 'Worker',
            },
        ),
    ]
