# Generated by Django 5.2 on 2025-05-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoryelement_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryelement',
            name='icon',
            field=models.ImageField(blank=True, default='core/elemento_predeterminado.jpg', null=True, upload_to='category_element_icons/'),
        ),
    ]
