# Generated by Django 5.2 on 2025-05-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_table_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstate',
            name='state',
            field=models.CharField(choices=[('Waiting to be cooked', 'Waiting to be cooked'), ('Waiting to be delivered', 'Waiting to be delivered')], max_length=50),
        ),
    ]
