# Generated by Django 5.2 on 2025-05-26 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_orderstate_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bar',
            name='position_bottom_right_X',
        ),
        migrations.RemoveField(
            model_name='bar',
            name='position_bottom_right_Y',
        ),
        migrations.RemoveField(
            model_name='bar',
            name='position_top_left_X',
        ),
        migrations.RemoveField(
            model_name='bar',
            name='position_top_left_Y',
        ),
        migrations.RemoveField(
            model_name='table',
            name='position_x',
        ),
        migrations.RemoveField(
            model_name='table',
            name='position_y',
        ),
        migrations.RemoveField(
            model_name='table',
            name='type',
        ),
        migrations.CreateModel(
            name='BarCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='core.bar')),
            ],
            options={
                'db_table': 'BarCell',
                'unique_together': {('x', 'y', 'bar')},
            },
        ),
        migrations.CreateModel(
            name='TableCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='core.table')),
            ],
            options={
                'db_table': 'TableCell',
                'unique_together': {('x', 'y', 'table')},
            },
        ),
    ]
