# Generated by Django 5.2 on 2025-05-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_worker_login_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='authentication_code',
            field=models.CharField(default=12345, max_length=5),
            preserve_default=False,
        ),
    ]
