# Generated by Django 5.2 on 2025-06-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_table_authentication_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryelement',
            name='type',
            field=models.CharField(choices=[('First plate', 'First plate'), ('Second plate', 'Second plate'), ('Dessert', 'Dessert')], default='First plate', max_length=20),
            preserve_default=False,
        ),
    ]
