# Generated by Django 5.2 on 2025-06-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_categoryelement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryelement',
            name='type',
            field=models.CharField(choices=[('To share', 'To share'), ('First plate', 'First plate'), ('Second plate', 'Second plate'), ('Dessert', 'Dessert'), ('Drink', 'Drink')], max_length=20),
        ),
    ]
