# Generated by Django 5.2 on 2025-06-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_categoryelement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstate',
            name='state',
            field=models.CharField(choices=[('Waiting to be cooked', 'Waiting to be cooked'), ('Waiting to be served', 'Waiting to be served'), ('Waiting to be send to cook', 'Waiting to be send to cook'), ('Delivered, Enjoy your meal!', 'Delivered, Enjoy your meal!')], max_length=50),
        ),
    ]
