# Generated by Django 5.2 on 2025-06-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_orderstate_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='allergen_icons/')),
            ],
            options={
                'verbose_name': 'Allergen',
                'verbose_name_plural': 'Allergens',
                'db_table': 'Allergen',
            },
        ),
        migrations.AlterField(
            model_name='orderstate',
            name='state',
            field=models.CharField(choices=[('Waiting to be cooked', 'In the kitchen...'), ('Waiting to be served', 'Waiter is on its way...'), ('Waiting to be send to cook', 'Awaiting confirmation...'), ('Delivered, Enjoy your meal!', 'Delivered, Enjoy!')], max_length=50),
        ),
        migrations.AddField(
            model_name='categoryelement',
            name='allergens',
            field=models.ManyToManyField(blank=True, related_name='get_Allergen_Category_Elements', to='core.allergen'),
        ),
    ]
