# Generated by Django 5.2 on 2025-06-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_allergen_alter_orderstate_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryelement',
            name='recipe',
            field=models.TextField(default='Default'),
            preserve_default=False,
        ),
    ]
