# Generated by Django 5.2 on 2025-06-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_categoryelement_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='open',
            field=models.BooleanField(default=False),
        ),
    ]
