# Generated by Django 5.2 on 2025-06-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_table_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='calling_waiter',
            field=models.BooleanField(default=False),
        ),
    ]
